version: "3"
services:
  app:
    image: node:latest
    environment:
      TZ: Europe/Paris
      NOTION_API_TOKEN: $NOTION_TOKEN
      NOTION_DB_ID: $DATABASE_ID
      GITHUB_REPOSITORY: $GITHUB_REPOSITORY
    volumes:
      - .:/app
    working_dir: /app
